---
abstract: 'Dumps data as one line string'
author:
  - 'Hiroki Honda <cside.story@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.0.0, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Dumper-OneLine
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Data::Dumper::OneLine:
    file: lib/Data/Dumper/OneLine.pm
    version: '0.02'
requires:
  perl: '5.008005'
resources:
  bugtracker: https://github.com/Cside/Data-Dumper-OneLine/issues
  homepage: https://github.com/Cside/Data-Dumper-OneLine
  repository: git://github.com/Cside/Data-Dumper-OneLine.git
version: '0.02'
x_authority: cpan:CSIDE
